### PR TITLE
Bot reply

### PR DESCRIPTION
**Pull request by Trenar**
Hi,
as mentioned in #91, I implemented a reply of the bot on incoming media. There is a new config file parameter `botReply` for it. ( :+1: :movie_camera: for videos, :+1: :camera_flash: for images) 

Since the bot.js changed pretty much in order to handle documents as gifs, I created this PR to this feature branch #85 . It is a very minimalistic implementation, which can simply be merged into that branch.

@gegu @LoiX07, I'd need your help for the vienna slang and french strings :)

### CODE REVIEW

**Comment by Trenar** [comment]
BTW, how are missing strings in the language files are handled? No fallback to English for now, right?

**Comment by gegu** [comment]
Nice idea :+1 

But I think we should differentiate between interface and bot language. The sender does not necessarily have to use the same language as configured for TeleFrame.
In my opinion, it would be better to define the language files for bot communication separately.
I'll take a look at this.

**Comment by LoiX07** [comment]
I'll have a look for the French translation !

**Comment by LoiX07** [comment]
Done

**Comment by Trenar** [comment]
Why did you close this PR?

**Comment by gegu** [comment]
I am sorry. The PR was closed when I merged feature/document-assets to develop.
But I'm looking at it right now. I'll get the changes from your repo.

**Comment by Trenar** [comment]
Okay :smile: Don't use my fork's develop branch, but the bot-reply branch

**Pull request closed without merging**
