### PR TITLE
File deletion

### PR DESCRIPTION
**Pull request by Trenar**
As requested for #51, I added a parameter to the config file. This makes this PR non-compatible with previous releases

(Sorry, if I made a mistake with this PR, I'm not very familiar with the git-workflow...)

### CODE REVIEW

**Comment by LukeSkywalker92** [comment]
I think we should wait for #46. can you try to merge #46 into your branch to see if there are conflicts?

**Comment by LukeSkywalker92** [comment]
#46  is merged to develop. so you can fix the conflicts now

**Comment by Trenar** [comment]
Conflicts are fixed, should be mergeable now. However, I couldn't test it in a raspi, only on my Linux machine w/o touch support but I think it makes no difference for testing this feature.

**Comment by LukeSkywalker92** [comment]
I’m going to test it later, but pleas add an entry to the README.md.

**Comment by Trenar** [comment]
Ready for merge

**Comment by gegu** [comment]
@Trenar please add a documented entry for the new configuration option to the `defaultConfig.js`, then I will merge your PR

**Comment by Trenar** [comment]
Done. Thanks for your work :)

**Pull request merged**
