### PR TITLE
Feature/touch controll bar

### PR DESCRIPTION
**Pull request by gegu**
I have worked on a few touchbar improvements. What do you think about it?

All things are optional and have no conflicts using the config.js from the master branch.

One more question about extending static texts:

What do you think about to separate the text constants to files i.e. config/i18n/de.js and define the english ones in the code as default/fallback? config.js gets a language option -`language: 'de'?`
This can be implemented without affecting the config.js currently in use.

### CODE REVIEW

**Comment by LukeSkywalker92** [comment]
Very nice work 👍🏼

**Comment by LukeSkywalker92** [comment]
Can we merge this?

**Comment by Trenar** [comment]
Hi Luke and gegu,
I tried the touch_controll_bar branch of gegu's fork and could not get the control-bar to work.. When I touch the screen, a grey bar is shown but no keys on it. I used the default config. Is this related to me making a mistake or a bug? 

Setup: RasPi 3A+, SunFounder 10.1" Display

**Comment by gegu** [comment]
> 
> 
> Can we merge this?

Yes of course I would like to.

I just pushed my latest changes.

Should I push that into your feature/touch-controll-bar, too?

**Comment by LukeSkywalker92** [comment]
I tested your last changes. But what I don't see is the confirmation dialog for deleting images and restart/shutdown.

**Comment by gegu** [comment]
The confirmation messages are not activated by default, But I can change that quickly.
If you are using the sample configuration, it should work.

**Comment by LukeSkywalker92** [comment]
Ok I’m going to try it again 😂 I think we should add default values for all settings in the future to the code. This would make the config.js more lightweight.

**Comment by LukeSkywalker92** [comment]
ok it works. Nice work :+1:

**Pull request merged**
