### PR TITLE
Whitelisting of Chat Ids

### PR DESCRIPTION
**Pull request by s00500**
Hey there, really nice project!!!!
here is another Luke, from Austria that has a very similar granny situation

I added the whitelist feature as mentioned in #10 

When you say "hi" to the bot it will tell you the chat id and you can then put it into the config very easily

I also tested the system under node 11.8.0, and it seems to work fine fyi

Thanks for this cool project, saved me some work =D

### CODE REVIEW

**Comment by LukeSkywalker92** [comment]
Hey Luke ;)

thank's for your work. This is a real enhancement. But could you please add some instructions to the README as well? Then i'm going to merge it.

I'm happy that you like the project. I think there are many other out there with a similar granny situation :laughing:

Best
Luke

**Comment by s00500** [comment]
added :-)

**Comment by s00500** [comment]
Closes #10

**Comment by LukeSkywalker92** [comment]
👍

**Pull request merged**
