### PR TITLE
Sunfounder screen config

### LINKED ISSUE #93: New screen definition
Sorry, I'm not getting along with github very well yet, so I don't want to make any pull requests or merges.

It would be great if you look at my suggestion and hopefully  include it in the project.

I took up Trenar's good idea and implemented the power on/off function for the Sunfounder HDMI display via optocoupler.

In this context the following 'files' were created:

- New screen definition file
- Shell Skript from Trenar adapted to my individual configuration
- Circuit diagram
- Board layout
- Datasheet optocoupler
- Two Photos

I also noticed that the wiringpi extension used in the script needs to be updated on the Raspberry Pi 4 first.

This may need to be included in the installer script and works as follows:

```
cd /tmp
wget https://project-downloads.drogon.net/wiringpi-latest.deb
sudo dpkg -i wiringpi-latest.deb
```
[Screen definition Sunfounder 10.1 hdmi display.zip](https://github.com/LukeSkywalker92/TeleFrame/files/4020901/Screen.definition.Sunfounder.10.1.hdmi.display.zip)

### PR DESCRIPTION
**Pull request by Trenar**
closes #93

### CODE REVIEW

**Comment by gegu** [comment]
We can't implement it that way. If the pin has been adjusted in the screen configuration, TeleFrame can no longer be updated without manual intervention. 

In #97 I provided the requirements for dynamic initialization. Please let me know if this meets your requirements. If so, then I will merge this PR, #85 and #90

**Comment by sohamakl** [comment]
Thanks for the support. For me it's a good solution.

**Comment by Trenar** [comment]
Fine for me as well. @sohamakl , did you already tested it?

**Comment by sohamakl** [comment]
Yes, but with an old release of TeleFrame and manuel changes. In my case I had to change the bash command from `exec("bash ../tools/screen_switch.sh"` to `exec("bash ./tools/screen_switch.sh"`

Sunday evening I can continue testing.

**Comment by Trenar** [comment]
Okay, that one is fixed.. 
I can't test display specific code anymore since all my three entities of the frame are gone :cry: The last one left me today.. Now I can only test on my notebook. btw @gegu is there a possibility to use the touchbar without a touchscreen but with the cursor?

**Comment by sohamakl** [comment]
Off topic but could you explain how to start this project on a windows pc.

**Comment by Trenar** [comment]
Windows or Unix? I can't help with Windows, und Linux (Ubuntu) I just clone via Terminal (run `git clone https://github.com/LukeSkywalker92/TeleFrame`, change to that newly created directory, create a config.json and then run `npm install` and `npm start`.

**Comment by sohamakl** [comment]
Okay, l’m using windows :-(

**Comment by LukeSkywalker92** [comment]
> I can't test display specific code anymore since all my three entities of the frame are gone 😢 The last one left me today.. Now I can only test on my notebook. btw @gegu is there a possibility to use the touchbar without a touchscreen but with the cursor?

You just need to open the dev tools in electron (ctrl+alt+i) and open the device toolbar, then clicks are treated like touches.

**Comment by LukeSkywalker92** [comment]
> Okay, l’m using windows :-(

It should be the same but you need to install git (https://git-scm.com)

**Comment by mistau** [comment]
While I cannot test this one as I don't own the according display the integration looks perfect.

**Comment by gegu** [comment]
@Trenar do you want to adjust your PR so that the configuration is adopted?

**Comment by Trenar** [comment]
Yes, I'll do if I find the time

**Comment by gegu** [comment]
Okay, I didn't mean to stress you out ☺️

**Comment by Trenar** [comment]
Finally.. I hope I made no mistakes, it's been a while...

**Comment by gegu** [comment]
👍 Looks good. Merged

**Pull request merged**
