### PR TITLE
Support receiving images/videos sent as subtype 'document'

### PR DESCRIPTION
**Pull request by gegu**
Images and videos are handled further if they were sent as documents. So it is possible to output animated GIF's as suggested in #78. Images in PNG and GIF format which use transparency can also be sent.

### CODE REVIEW

**Comment by Trenar** [comment]
Wow, you're fast. Thanks a lot, I'll test it as soon as I get my fingers back on a TeleFrame given away on Christmas :D

**Comment by Trenar** [comment]
Nice implementation @gegu .
However, an animated .gif is shown exactly as long as <interval> is chosen. That means, if the gif is shorter, the very last frame is held until <interval> is reached and if it is longer, it is simply cutted at the <interval>. This may not be too bad for an interval of (lets say) 30 seconds, but should be handled somehow (in the renderer?).

**Comment by Trenar** [comment]
New tests showed that this behavior (last frame freezed as long as interval or video cropped) also shows up for mp4 videos... Could be related to #86 and the other renderer?

**Comment by gegu** [comment]
Yes, in #86 the duration of the video was not taken into account. This was fixed.

**Pull request merged**
